const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

// placeholder-data.ts

const budgets = [
  {
    id: '627b7890-8488-444a-9c2b-6893e25b184b',
    category: 'Entertainment',
    maximum_spend: 5000, 
    theme: '#277C78',
    amount: 1500,
  },
  {
    id: 'f888360d-886d-47c3-94c3-2b28c8959663',
    category: 'Bills',
    maximum_spend: 75000,
    theme: '#82C9D7',
    amount: 75000,
  },
  {
    id: '43d9c79e-4770-449e-8c33-66236b281f6d',
    category: 'Dining Out',
    maximum_spend: 30000,
    theme: '#F2CDAC',
    amount: 21250,
  },
];

// const pots = [
//   {
//     id: 'd9620704-5f5a-4e89-980b-8d6c70f07421',
//     name: 'Savings',
//     target: 200000, 
//     theme: '#277C78',
//     total: 159000,
//   },
//   {
//     id: '01d4d80a-9d9e-4712-9861-f3f508736d76',
//     name: 'New Laptop',
//     target: 100000,
//     theme: '#626070',
//     total: 10000,
//   },
// ];

// @/app/lib/data.ts
export const TRANSACTIONS = [
  {
    id: '1',
    name: 'Emma Richardson',
    image: "/assets/images/avatars/emma-richardson.jpg",
    category: 'General',
    date: '19 Aug 2023',
    amount: 75.50,
    isIncome: false,
  },
  {
    id: '2',
    name: 'Flavor Fiesta',
    image: "/assets/images/avatars/flavor-fiesta.jpg",
    category: 'Dining Out',
    date: '19 Aug 2023',
    amount: 37.00,
    isIncome: false,
  },
  {
    id: '3',
    name: 'Ethan Clark',
    image: "/assets/images/avatars/ethan-clark.jpg",
    category: 'General',
    date: '18 Aug 2023',
    amount: 500.00,
    isIncome: true,
  },
  {
    id: '4',
    name: 'Aqua Flow Utilities',
    image: "/assets/images/avatars/aqua-flow-utilities.jpg",
    category: 'Bills',
    date: '17 Aug 2023',
    amount: 120.00,
    isIncome: false,
  },
  {
    id: '5',
    name: 'James Thompson',
    image: "/assets/images/avatars/james-thompson.jpg",
    category: 'Entertainment',
    date: '17 Aug 2023',
    amount: 15.99,
    isIncome: false,
  },
  {
    id: '6',
    name: 'Ella Phillips',
    image: "/assets/images/avatars/ella-phillips.jpg",
    category: 'Personal Care',
    date: '16 Aug 2023',
    amount: 45.00,
    isIncome: false,
  },
  {
    id: '7',
    name: 'Sebastian Cook',
    image: "/assets/images/avatars/sebastian-cook.jpg",
    category: 'Shopping',
    date: '16 Aug 2023',
    amount: 399.99,
    isIncome: false,
  },
  {
    id: '8',
    name: 'Swift Ride Share',
    image: "/assets/images/avatars/swift-ride-share.jpg",
    category: 'Transportation',
    date: '15 Aug 2023',
    amount: 22.50,
    isIncome: false,
  },
  {
    id: '9',
    name: 'Daniel Carter',
    image: "/assets/images/avatars/daniel-carter.jpg",
    category: 'General',
    date: '14 Aug 2023',
    amount: 1000.00,
    isIncome: true,
  },
  {
    id: '10',
    name: 'Savory Bites Bistro',
    image: "/assets/images/avatars/savory-bites-bistro.jpg",
    category: 'Dining Out',
    date: '14 Aug 2023',
    amount: 55.20,
    isIncome: false,
  },
  {
    id: '11',
    name: 'Lily Ramirez',
    image: "/assets/images/avatars/lily-ramirez.jpg",
    category: 'Shopping',
    date: '13 Aug 2023',
    amount: 125.00,
    isIncome: false,
  },
  {
    id: '12',
    name: 'Ecofuel Energy',
    image: "/assets/images/avatars/ecofuel-energy.jpg",
    category: 'Bills',
    date: '12 Aug 2023',
    amount: 85.00,
    isIncome: false,
  },
  {
    id: '13',
    name: 'Liam Hughes',
    image: "/assets/images/avatars/liam-hughes.jpg",
    category: 'Personal Care',
    date: '12 Aug 2023',
    amount: 30.00,
    isIncome: false,
  },
  {
    id: '14',
    name: 'Pixel Playground',
    image: "/assets/images/avatars/pixel-playground.jpg",
    category: 'Entertainment',
    date: '11 Aug 2023',
    amount: 25.00,
    isIncome: false,
  },
  {
    id: '15',
    name: 'Yuna Kim',
    image: "/assets/images/avatars/yuna-kim.jpg",
    category: 'General',
    date: '11 Aug 2023',
    amount: 250.00,
    isIncome: true,
  },
   {
    id: '16',
    name: 'Emma Richardson',
    image: "/assets/images/avatars/emma-richardson.jpg",
    category: 'General',
    date: '19 Aug 2023',
    amount: 75.50,
    isIncome: false,
  },
  {
    id: '17',
    name: 'Flavor Fiesta',
    image: "/assets/images/avatars/flavor-fiesta.jpg",
    category: 'Dining Out',
    date: '19 Aug 2023',
    amount: 37.00,
    isIncome: false,
  },
  {
    id: '18',
    name: 'Ethan Clark',
    image: "/assets/images/avatars/ethan-clark.jpg",
    category: 'General',
    date: '18 Aug 2023',
    amount: 500.00,
    isIncome: true,
  },
  {
    id: '19',
    name: 'Aqua Flow Utilities',
    image: "/assets/images/avatars/aqua-flow-utilities.jpg",
    category: 'Bills',
    date: '17 Aug 2023',
    amount: 120.00,
    isIncome: false,
  },
  {
    id: '20',
    name: 'James Thompson',
    image: "/assets/images/avatars/james-thompson.jpg",
    category: 'Entertainment',
    date: '17 Aug 2023',
    amount: 15.99,
    isIncome: false,
  },
  {
    id: '21',
    name: 'Ella Phillips',
    image: "/assets/images/avatars/ella-phillips.jpg",
    category: 'Personal Care',
    date: '16 Aug 2023',
    amount: 45.00,
    isIncome: false,
  },
  {
    id: '22',
    name: 'Sebastian Cook',
    image: "/assets/images/avatars/sebastian-cook.jpg",
    category: 'Shopping',
    date: '16 Aug 2023',
    amount: 399.99,
    isIncome: false,
  },
  {
    id: '23',
    name: 'Swift Ride Share',
    image: "/assets/images/avatars/swift-ride-share.jpg",
    category: 'Transportation',
    date: '15 Aug 2023',
    amount: 22.50,
    isIncome: false,
  },
  {
    id: '24',
    name: 'Daniel Carter',
    image: "/assets/images/avatars/daniel-carter.jpg",
    category: 'General',
    date: '14 Aug 2023',
    amount: 1000.00,
    isIncome: true,
  },
  {
    id: '25',
    name: 'Savory Bites Bistro',
    image: "/assets/images/avatars/savory-bites-bistro.jpg",
    category: 'Dining Out',
    date: '14 Aug 2023',
    amount: 55.20,
    isIncome: false,
  },
  {
    id: '26',
    name: 'Lily Ramirez',
    image: "/assets/images/avatars/lily-ramirez.jpg",
    category: 'Shopping',
    date: '13 Aug 2023',
    amount: 125.00,
    isIncome: false,
  },
  {
    id: '27',
    name: 'Ecofuel Energy',
    image: "/assets/images/avatars/ecofuel-energy.jpg",
    category: 'Bills',
    date: '12 Aug 2023',
    amount: 85.00,
    isIncome: false,
  },
  {
    id: '28',
    name: 'Liam Hughes',
    image: "/assets/images/avatars/liam-hughes.jpg",
    category: 'Personal Care',
    date: '12 Aug 2023',
    amount: 30.00,
    isIncome: false,
  },
  {
    id: '29',
    name: 'Pixel Playground',
    image: "/assets/images/avatars/pixel-playground.jpg",
    category: 'Entertainment',
    date: '11 Aug 2023',
    amount: 25.00,
    isIncome: false,
  },
  {
    id: '30',
    name: 'Yuna Kim',
    image: "/assets/images/avatars/yuna-kim.jpg",
    category: 'General',
    date: '11 Aug 2023',
    amount: 250.00,
    isIncome: true,
  }
];

export const BILLS = [
  {
    id: '1',
    name: 'Bravo Zen Spa',
    image: "/assets/images/avatars/serenity-spa-and-wellness.jpg",
    category: 'General',
    date: '2024-08-03T19:51:00', // Standard format
    amount: 70,
    isPaid: true
  },
  {
    id: '2',
    name: 'Education',
    image: "/assets/images/avatars/elevate-education.jpg",
    category: 'General',
    date: '2024-08-03T19:51:00',
    amount: 70,
    isPaid: true
  },
  {
    id: '3',
    name: 'Spark Electric', // Changed name to match the image path
    image: "/assets/images/avatars/spark-electric-solutions.jpg",
    category: 'General',
    date: '2024-08-03T19:51:00',
    amount: 70,
    isPaid: true
  },
  {
    id: '4',
    name: 'Delta Taxi',
    image: "/assets/images/avatars/swift-ride-share.jpg",
    category: 'General',
    date: '2024-08-06T19:51:00', 
    amount: 250,
    isPaid: false 
  },
]

export { users, budgets };